services:
  # postgres
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./data/postgres:/var/lib/postgresql/initdb.d
      - ./data/postgres/backups:/backups
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    networks:
      app-network:
        
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      app-network:
  
  # Mailpit
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      app-network:

# Volumes
volumes:
  postgres_data:
  postgres:
  postgres_backups:
  

# Networks
networks:
  app-network:
    driver: bridge
